(ns banking.render-html
  "Build-time HTML renderer for `docs/samples/operator-console.html`.

  Closes flagship checklist item 2 (com-junkawasaki/root ADR-2607189300):
  this repo shipped a `docs/samples/operator-console.html` that NO
  generator in this repo had ever produced -- it showed accounts `A1`/
  `A2` (\"Acme\", \"Beta Co\"), postings `P1`/`P2` and a clearing batch
  `C1`, none of which exist anywhere in `banking.store/demo-data`, and
  no governor hold at all. It was hand-written. This namespace replaces
  it with a page generated by actually running the actor.

  Everything rendered here is real output of a real run of
  `banking.operation` -> `banking.governor` -> `banking.store` through
  `langgraph.graph/run*`:

    - account rows are `banking.store/all-accounts` AFTER the run;
    - the IBAN validity column is recomputed at render time by calling
      `banking.registry/iban-checksum-invalid?`, the same ISO 7064
      MOD 97-10 function the governor calls;
    - the action-gate rows are produced by CALLING `banking.phase/gate`
      with a clean and with a held governor verdict;
    - the rollout-phase rows are read out of `banking.phase/phases`;
    - the HARD-check rows are grouped out of the run's real
      `:governor-hold` facts (no rule is named as a literal);
    - jurisdiction coverage is `banking.facts/coverage` over the
      jurisdictions the seeded accounts actually carry;
    - the approver-attribution column is DERIVED by reading the store
      back at render time (see `approver-disclosure`);
    - the settlement / interbank-message drafts are the records
      `banking.registry` actually minted.

  Scenario shape (adapted from this repo's own `banking.sim` demo
  driver, `clojure -M:dev:run`, which was run BEFORE this file was
  written and confirmed to produce a sensible ledger against the real
  seeded account ids `account-1`..`account-5`):

    - account-1 (JPN, valid IBAN, no sanctions flag) walks a full clean
      lifecycle -- intake (auto-commits at phase 3, no capital risk),
      AML/KYC evidence verification (escalates, approved), sanctions
      screening (escalates, approved), settlement posting and interbank
      message dispatch (BOTH always escalate at every phase, both
      approved);
    - account-5's evidence verification is REJECTED by the human
      approver -- the SOFT gate's other outcome, to contrast with a
      HARD hold that never reaches a human at all;
    - six distinct HARD governor rules actually fire -- every numbered
      HARD check in `banking.governor` plus both double-actuation
      guards (see `min-distinct-hard-rules`);
    - account-5's sanctions hold is produced by a real cross-reference
      into `cloud-itonami-isic-8291` through `banking.corporate-intel`,
      not by a local flag -- the page proves that by showing that
      account-5's own `:sanctions-flag-unresolved?` field is false.

  Build-time invariants (`-main` THROWS, it does not warn):
    1. the run must produce at least one real `:governor-hold` fact;
    2. it must fire at least `min-distinct-hard-rules` DISTINCT HARD
       rules -- an evidence floor, so a governor change that silently
       stops firing a check fails the build instead of quietly
       rendering a thinner page;
    3. no run that HARD-held may ALSO have asked a human (no
       `:approval-requested` in the same run's audit) -- the claim
       \"HARD holds never reach a human\" is measured, not asserted;
    4. every HARD-check row rendered must trace to a rule actually
       present in the ledger;
    5. the SOFT gate must have shown BOTH outcomes (one approval
       granted AND one rejected) -- otherwise the approval trail and
       the approver probe are vacuous tables that read like a pass;
    6. the run must have minted at least one registry draft of each
       kind, so the drafts section cannot be silently empty.

  Deterministic: no timestamps, no random ids, byte-identical across
  reruns against the same seed (verify by diffing two consecutive
  runs into scratch files).

  Usage: `clojure -M:dev:render-html [out-file]`
  (default `docs/samples/operator-console.html`)."
  (:require [jp-go-dds.skin]
            [clojure.string :as str]
            [banking.store :as store]
            [banking.facts :as facts]
            [banking.phase :as phase]
            [banking.governor :as governor]
            [banking.registry :as registry]
            [banking.operation :as op]
            [banking.bankingadvisor :as bankingadvisor]
            [banking.corporate-intel :as corporate-intel]
            [langgraph.graph :as g]))

(def ^:private operator
  {:actor-id "op-1" :actor-role :banking-operator :phase 3})

(def min-distinct-hard-rules
  "Evidence floor for invariant 2. The scenario below drives all six of
  `banking.governor`'s HARD rules. If a governor/store/advisor change
  makes fewer of them fire, the build FAILS rather than rendering a
  quietly thinner page. Raise this when the scenario grows; never
  lower it to make a build pass."
  6)

(def ^:private cross-referenced-account
  "The account whose sanctions hold must come from the
  `cloud-itonami-isic-8291` cross-reference rather than from a local
  flag. Named here only so the renderer can go and CHECK that claim
  against the store; the claim itself is never printed unless the
  check passes."
  "account-5")

;; ----------------------------- the real run -----------------------------

(defn- exec!
  "One supervised operation = one langgraph run. Returns the run result;
  `runs` accumulates them so the renderer can read each run's own audit
  channel -- `:approval-granted` facts never reach the store ledger
  (see `banking.operation`'s `:commit` node, which appends only the
  commit fact), so the approval trail cannot be reconstructed from the
  ledger alone."
  [runs actor tid request]
  (let [r (g/run* actor {:request request :context operator} {:thread-id tid})]
    (swap! runs conj (assoc (select-keys request [:op :subject])
                            :thread tid
                            :audit (get-in r [:state :audit])
                            :disposition (get-in r [:state :disposition])))
    r))

(defn- resume!
  "Resume a run paused at `:request-approval` with a real human decision."
  [runs actor tid status by]
  (let [r (g/run* actor {:approval {:status status :by by}}
                  {:thread-id tid :resume? true})]
    (swap! runs conj {:thread tid :resume? true
                      :audit (get-in r [:state :audit])
                      :disposition (get-in r [:state :disposition])})
    r))

(defn run-demo!
  "Runs a fresh seeded store through a scenario reaching every
  disposition this actor can produce. Returns `{:db .. :runs [..]}`;
  every field the renderer reads is real governor/store/langgraph
  output.

  The last screening is driven by a SECOND actor whose advisor has
  `banking.corporate-intel/screen` wired in, so account-5's HARD hold
  is produced by an actual governed `:disclosure/screen-name` call
  into `cloud-itonami-isic-8291` (whose own DisclosureGovernor
  escalates the sanctions hit to ITS OWN reviewer -- reported back as
  `:pending-human-review?`, which this domain's two-valued vocabulary
  must treat as unresolved), not by a local flag."
  []
  (let [db (store/seed-db)
        runs (atom [])
        actor (op/build db)
        ;; second actor, SAME SSoT, advisor wired to the real 8291 actor
        intel-actor (corporate-intel/build)
        intel-op (op/build db {:advisor (bankingadvisor/mock-advisor
                                         {:corporate-intel-screen
                                          #(corporate-intel/screen % {:actor intel-actor})})})]

    ;; --- account-1: full clean lifecycle ------------------------------
    (exec! runs actor "a1-intake"
           {:op :account/intake :subject "account-1"
            :patch {:id "account-1" :holder-name "Sato Ichiro"}})

    (exec! runs actor "a1-verify" {:op :compliance/verify :subject "account-1"})
    (resume! runs actor "a1-verify" :approved "op-1")

    (exec! runs actor "a1-screen" {:op :sanctions/screen :subject "account-1"})
    (resume! runs actor "a1-screen" :approved "op-1")

    (exec! runs actor "a1-settle" {:op :actuation/post-settlement :subject "account-1"})
    (resume! runs actor "a1-settle" :approved "op-1")

    (exec! runs actor "a1-dispatch" {:op :actuation/dispatch-interbank-message :subject "account-1"})
    (resume! runs actor "a1-dispatch" :approved "op-1")

    ;; --- HARD: fabricated jurisdiction spec-basis ---------------------
    (exec! runs actor "a2-verify" {:op :compliance/verify :subject "account-2" :no-spec? true})

    ;; --- HARD: actuation before any evidence checklist is on file -----
    (exec! runs actor "a2-settle" {:op :actuation/post-settlement :subject "account-2"})

    ;; --- HARD: the account's own IBAN fails ISO 7064 MOD 97-10 --------
    (exec! runs actor "a3-verify" {:op :compliance/verify :subject "account-3"})
    (resume! runs actor "a3-verify" :approved "op-1")
    (exec! runs actor "a3-settle" {:op :actuation/post-settlement :subject "account-3"})

    ;; --- HARD: unresolved sanctions flag on file locally --------------
    (exec! runs actor "a4-screen" {:op :sanctions/screen :subject "account-4"})

    ;; --- HARD: double settlement / double dispatch of the same account -
    (exec! runs actor "a1-settle-again" {:op :actuation/post-settlement :subject "account-1"})
    (exec! runs actor "a1-dispatch-again" {:op :actuation/dispatch-interbank-message :subject "account-1"})

    ;; --- SOFT: clean proposal, human approver says NO -----------------
    (exec! runs actor "a5-verify" {:op :compliance/verify :subject cross-referenced-account})
    (resume! runs actor "a5-verify" :rejected "op-1")

    ;; --- HARD: sanctions unresolved via the 8291 cross-reference ------
    (exec! runs intel-op "a5-screen" {:op :sanctions/screen :subject cross-referenced-account})

    {:db db :runs @runs}))

;; ----------------------------- html helpers -----------------------------

(defn- esc [v]
  (-> (str v)
      (str/replace "&" "&amp;")
      (str/replace "<" "&lt;")
      (str/replace ">" "&gt;")))

(defn- kname [k] (if (keyword? k) (name k) (str k)))

(defn- code* [v] (str "<code>" (esc v) "</code>"))

(defn- row [& cells]
  (str "        <tr>" (str/join (map #(str "<td>" % "</td>") cells)) "</tr>"))

(defn- rows [xs] (str/join "\n" xs))

(defn- section [title lede headers body-rows]
  (str "  <section class=\"card\">\n"
       "    <h2>" title "</h2>\n"
       "    <p class=\"muted\">" lede "</p>\n"
       "    <table>\n"
       "      <thead><tr>" (str/join (map #(str "<th>" % "</th>") headers)) "</tr></thead>\n"
       "      <tbody>\n" body-rows "\n"
       "      </tbody>\n"
       "    </table>\n"
       "  </section>\n"))

;; ----------------------------- derived views -----------------------------

(defn- hard-holds [ledger] (filter #(= :governor-hold (:t %)) ledger))

(defn- hard-rule-groups
  "Groups the run's REAL `:governor-hold` facts by violated rule, in
  first-seen ledger order. Nothing here is a literal: if a rule stops
  firing, its row disappears (and `-main`'s evidence floor fails)."
  [ledger]
  (->> (for [f (hard-holds ledger)
             v (:violations f)]
         (assoc v :subject (:subject f) :op (:op f)))
       (reduce (fn [acc {:keys [rule detail subject op]}]
                 (if (contains? acc rule)
                   (-> acc
                       (update-in [rule :count] inc)
                       (update-in [rule :subjects] conj subject)
                       (update-in [rule :ops] conj op))
                   (assoc acc rule {:rule rule :detail detail :count 1
                                    :order (count acc)
                                    :subjects [subject] :ops [op]})))
               {})
       vals
       (sort-by :order)))

;; --- store approver attribution, DERIVED (never asserted) --------------

(defn- approver-in
  "Any value stored under an `approved-by` / `approved_by` key, whatever
  the key type -- this store mixes keyword-keyed payload maps with
  `banking.registry`'s string-keyed records, so the probe must not
  assume either."
  [m]
  (when (map? m)
    (some (fn [[k v]]
            (when (and v (contains? #{"approved-by" "approved_by"} (kname k))) v))
          m)))

(defn- registers-for
  "The SSoT registers a committed op of this kind actually writes, read
  back through the Store protocol. This is the probe: whether the
  approver survives is decided by what is IN these maps at render
  time, not by anything this namespace claims."
  [db op subject]
  (case op
    :account/intake     [(store/account db subject)]
    :compliance/verify  [(store/compliance-of db subject)]
    :sanctions/screen   [(store/sanctions-screen-of db subject)]
    :actuation/post-settlement
    (into [(store/account db subject)]
          (filter #(= subject (get % "account_id")) (store/settlement-history db)))
    :actuation/dispatch-interbank-message
    (into [(store/account db subject)]
          (filter #(= subject (get % "account_id")) (store/interbank-message-history db)))
    []))

(defn- register-names [op]
  (case op
    :account/intake     "account record (:account/upsert value)"
    :compliance/verify  "AML/KYC register (:compliance/set payload)"
    :sanctions/screen   "sanctions register (:sanctions-screen/set payload)"
    :actuation/post-settlement            "account record + settlement draft"
    :actuation/dispatch-interbank-message "account record + interbank-message draft"
    ""))

(defn- approval-trail
  "One row per human decision the run actually took. `:decided-by` is
  read off the run's own audit fact; `:retained` is read back OUT of
  the store. The two are reported separately on purpose -- a reader
  must be able to tell \"nobody approved\" from \"the store dropped
  it\"."
  [db runs]
  (let [by-thread (into {} (for [r runs :when (not (:resume? r))]
                             [(:thread r) r]))]
    (for [r runs
          :when (:resume? r)
          :let [f (last (filter #(#{:approval-granted :approval-rejected} (:t %)) (:audit r)))
                src (get by-thread (:thread r))
                o (:op src)
                s (:subject src)]
          :when f]
      {:thread (:thread r)
       :op o
       :subject s
       :outcome (:t f)
       :decided-by (:by f)
       :register (register-names o)
       :retained (when (= :approval-granted (:t f))
                   (some approver-in (registers-for db o s)))})))

(defn- approver-disclosure
  "The attribution sentence, DERIVED from the trail this run actually
  produced rather than stated as prose. Which registers keep the
  approver is a property of `banking.store/commit-record!`, not of
  this page: `:compliance/set` and `:sanctions-screen/set` persist the
  `:payload` whole (and the payload is where `banking.operation`'s
  `:request-approval` node puts `:approved-by`), while the actuation
  branches re-mint their record from the account id and jurisdiction
  through `banking.registry` and never read `:payload` at all. If that
  is changed, this sentence changes with it -- a hard-coded claim here
  would have become a lie the moment someone fixed the store."
  [trail]
  (let [granted (filter #(= :approval-granted (:outcome %)) trail)
        ops (fn [xs] (str/join ", " (map #(code* %) (distinct (map :op xs)))))
        kept (filter :retained granted)
        lost (remove :retained granted)]
    (cond
      (empty? granted)
      "No approval was granted in this run, so there is nothing to attribute."

      (empty? lost)
      (str "Measured on this run: the approver survived on every register written by "
           (ops kept) ".")

      (empty? kept)
      (str "Measured on this run: the approver was dropped by every register written by "
           (ops lost) " &mdash; it exists only on the audit fact.")

      :else
      (str "Measured on this run: the approver survived on the payload-backed registers written by "
           (ops kept) ", and was dropped by " (ops lost)
           " &mdash; those records are re-minted by <code>banking.registry</code> from the account id and "
           "jurisdiction alone, so the <code>:payload</code> carrying <code>approved-by</code> is never read. "
           "Where it was dropped the approver is shown from the audit fact and labelled as such, "
           "so “nobody approved” and “the store dropped it” cannot look the same."))))

(defn- cross-reference-note
  "The `cloud-itonami-isic-8291` sentence is only emitted if that hold
  is ACTUALLY in this run's ledger AND the account's own local
  sanctions flag is false -- i.e. only if the cross-reference is
  demonstrably what produced it. account-4's local flag keeps the RULE
  row alive either way, so the rule count alone cannot be trusted to
  notice the cross-reference silently going dark."
  [db ledger account-id]
  (let [a (store/account db account-id)
        held? (some (fn [f]
                      (and (= :governor-hold (:t f))
                           (= account-id (:subject f))
                           (some #{:sanctions-flag-unresolved} (:basis f))))
                    ledger)]
    (when (and held? a (not (:sanctions-flag-unresolved? a)))
      (str " The <code>" (esc account-id) "</code> hold was produced by an actual governed "
           "<code>:disclosure/screen-name</code> cross-reference into <code>cloud-itonami-isic-8291</code>, "
           "not by a local flag &mdash; that account's own "
           "<code>:sanctions-flag-unresolved?</code> field is <code>false</code>, as the accounts table above shows. "
           "8291's own DisclosureGovernor escalated the hit to ITS OWN reviewer; this domain's two-valued "
           "vocabulary has no “inconclusive” state, so a pending review must collapse onto "
           "<code>:unresolved</code> rather than onto a clear."))))

;; ----------------------------- rows -----------------------------

(defn- last-fact-for [ledger account-id]
  (last (filter #(= (:subject %) account-id) ledger)))

(defn- status-cell [ledger account-id]
  (let [f (last-fact-for ledger account-id)]
    (cond
      (nil? f) "<span class=\"muted\">no activity</span>"
      (= :governor-hold (:t f))
      (str "<span class=\"critical\">HARD hold &middot; "
           (esc (str/join ", " (map kname (:basis f)))) "</span>")
      (= :approval-rejected (:t f)) "<span class=\"warn\">approver rejected</span>"
      (= :committed (:t f)) "<span class=\"ok\">committed</span>"
      :else "<span class=\"muted\">in progress</span>")))

(defn- account-row
  [ledger {:keys [id holder-name iban jurisdiction sanctions-flag-unresolved?
                  settlement-posted? interbank-message-dispatched?
                  settlement-number message-number] :as a}]
  (row (code* id)
       (esc holder-name)
       (str (code* iban) " "
            ;; recomputed HERE, by the same ISO 7064 MOD 97-10 function
            ;; the governor calls -- not copied off the account record.
            (if (registry/iban-checksum-invalid? a)
              "<span class=\"critical\">MOD 97-10 fail</span>"
              "<span class=\"ok\">MOD 97-10 ok</span>"))
       (code* jurisdiction)
       (if sanctions-flag-unresolved?
         "<span class=\"critical\">unresolved</span>"
         "<span class=\"ok\">no local flag</span>")
       (if settlement-posted?
         (str "<span class=\"ok\">posted &middot; " (code* settlement-number) "</span>")
         "<span class=\"muted\">not posted</span>")
       (if interbank-message-dispatched?
         (str "<span class=\"ok\">dispatched &middot; " (code* message-number) "</span>")
         "<span class=\"muted\">not dispatched</span>")
       (status-cell ledger id)))

(defn- op-gate-row
  "Calls the REAL `banking.phase/gate` at the default phase for both a
  governor-clean and a governor-held base disposition, so the two
  middle columns are the gate's own answers, not a description of them."
  [op]
  (let [clean (phase/gate phase/default-phase {:op op} :commit)
        held  (phase/gate phase/default-phase {:op op} :hold)
        stakes? (contains? governor/high-stakes op)]
    (row (code* op)
         (case (:disposition clean)
           :commit "<span class=\"ok\">auto-commit when governor-clean</span>"
           :escalate (str "<span class=\"warn\">human approval</span>"
                          (when (:reason clean)
                            (str " <span class=\"muted\">&middot; " (esc (kname (:reason clean))) "</span>")))
           (str "<span class=\"critical\">hold</span>"
                (when (:reason clean)
                  (str " <span class=\"muted\">&middot; " (esc (kname (:reason clean))) "</span>"))))
         (str "<span class=\"critical\">" (esc (kname (:disposition held))) "</span>")
         (if stakes?
           "<span class=\"critical\">yes &middot; never auto at any phase</span>"
           "<span class=\"muted\">no</span>"))))

(defn- phase-row [[p {:keys [label writes auto]}]]
  (row (str "<span class=\"num\">" p "</span>")
       (esc label)
       (if (seq writes)
         (str/join " " (map #(code* %) (sort-by str writes)))
         "<span class=\"muted\">none</span>")
       (if (seq auto)
         (str/join " " (map #(code* %) (sort-by str auto)))
         "<span class=\"muted\">none &middot; every write needs a human</span>")))

(defn- hard-check-row [{:keys [rule detail count subjects]}]
  (row (code* rule)
       (str "<span class=\"num\">" count "</span>")
       (str/join " " (map #(code* %) (distinct subjects)))
       (esc detail)))

(defn- jurisdiction-row [iso3]
  (let [sb (facts/spec-basis iso3)]
    (row (code* iso3)
         (if sb (esc (:name sb)) "<span class=\"critical\">no spec-basis on file</span>")
         (if sb (esc (:owner-authority sb)) "<span class=\"muted\">&mdash;</span>")
         (if sb (esc (:legal-basis sb)) "<span class=\"muted\">&mdash;</span>")
         (if sb (str "<span class=\"num\">" (count (:required-evidence sb)) "</span>")
             "<span class=\"num\">0</span>")
         (if sb (code* (:provenance sb))
             "<span class=\"critical\">proposals citing it are HARD-held</span>"))))

(defn- approval-row [{:keys [op subject outcome decided-by register retained]}]
  (row (code* op)
       (code* subject)
       (if (= :approval-granted outcome)
         "<span class=\"ok\">approved</span>"
         "<span class=\"warn\">rejected</span>")
       (if decided-by (code* decided-by)
           "<span class=\"warn\">not recorded on the audit fact</span>")
       (esc register)
       (cond
         (not= :approval-granted outcome) "<span class=\"muted\">n/a &middot; nothing committed</span>"
         retained (str "<span class=\"ok\">retained &middot; " (code* retained) "</span>")
         decided-by (str "<span class=\"warn\">" (code* decided-by)
                         " &middot; audit only &mdash; not retained in the store record</span>")
         :else "<span class=\"critical\">no approver anywhere</span>")))

(defn- draft-row [r]
  (row (code* (get r "record_id"))
       (esc (get r "kind"))
       (code* (get r "account_id"))
       (esc (get r "jurisdiction"))
       (if (get r "immutable")
         "<span class=\"ok\">immutable</span>"
         "<span class=\"warn\">mutable</span>")))

(defn- ledger-row [{:keys [t op subject basis summary]}]
  (row (case t
         :committed "<span class=\"ok\">committed</span>"
         :governor-hold "<span class=\"critical\">governor-hold</span>"
         :approval-rejected "<span class=\"warn\">approval-rejected</span>"
         (str "<span class=\"muted\">" (esc (kname t)) "</span>"))
       (code* (or op :n-a))
       (code* subject)
       (esc (str/join ", " (map kname basis)))
       (esc (or summary ""))))

;; ----------------------------- rendering -----------------------------

(defn render
  "Renders the whole document from a `{:db .. :runs ..}` produced by
  `run-demo!` (or any other real scenario)."
  [{:keys [db runs]}]
  (let [ledger (vec (store/ledger db))
        accounts (store/all-accounts db)
        used-jurisdictions (vec (distinct (map :jurisdiction accounts)))
        cov (facts/coverage used-jurisdictions)
        groups (hard-rule-groups ledger)
        trail (approval-trail db runs)
        n-hard (count (hard-holds ledger))]
    (str
     "<html lang=\"en\"><head><meta charset=\"utf-8\">"
     "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
     "<title>cloud-itonami-isic-6419 &middot; community banking operator console</title><style>"
     (jp-go-dds.skin/dds+skin)
     "</style></head><body>\n"
     "<header class=\"bar\">\n"
     "  <h1>Other monetary intermediation (ISIC 6419) — Community Banking Operator Console</h1>\n"
     "  <span class=\"badge\">read-only sample · governor-gated · settlement posting and interbank-message dispatch are always human-approved</span>\n"
     "</header>\n"
     "<main>\n"

     (section
      "Accounts (SSoT snapshot)"
      (str "Every row is <code>banking.store/all-accounts</code> after the run — build-time-generated by "
           "<code>banking.render-html</code> (<code>clojure -M:dev:render-html</code>), never hand-written. "
           "The IBAN column is not copied off the record: it is recomputed here by calling "
           "<code>banking.registry/iban-checksum-invalid?</code>, the same ISO 7064 MOD 97-10 implementation "
           "the governor calls independently before any settlement is posted.")
      ["Account" "Holder" "IBAN (ISO 7064 MOD 97-10, recomputed)" "Jurisdiction"
       "Local sanctions flag" "Settlement" "Interbank message" "Last op status"]
      (rows (map (partial account-row ledger) accounts)))

     (section
      "Action gate — what the phase gate actually answers"
      (str "The two middle columns are produced by CALLING <code>banking.phase/gate</code> at phase "
           phase/default-phase " (<code>" (esc (:label (get phase/phases phase/default-phase)))
           "</code>) with a clean and with a HARD-held governor verdict. A HARD violation always stays a "
           "hold — the phase gate can only add caution, never remove it. The right-most column is membership "
           "of <code>banking.governor/high-stakes</code>: two independent layers agree that posting a real "
           "settlement and dispatching a real interbank message are always a human call.")
      ["Op" "Governor clean →" "Governor HARD →" "High-stakes actuation"]
      (rows (map op-gate-row (sort-by str phase/write-ops))))

     (section
      "Rollout phases"
      (str "Read straight out of <code>banking.phase/phases</code>. Note that "
           "<code>:actuation/post-settlement</code> and <code>:actuation/dispatch-interbank-message</code> "
           "appear in no phase's auto set, including the last one — a permanent structural fact, not a "
           "milestone still to come.")
      ["Phase" "Label" "Writes allowed" "May auto-commit when governor-clean"]
      (rows (map phase-row (sort-by key phase/phases))))

     (section
      (str "HARD governor holds fired by this run (" n-hard " holds, " (count groups) " distinct rules)")
      (str "Grouped out of the run's real <code>:governor-hold</code> facts; the detail text is the "
           "governor's own. A HARD violation is un-overridable: it never reaches a human approver at all, "
           "which the build verifies structurally (no <code>:approval-requested</code> in any held run's "
           "audit channel) rather than claiming here."
           (cross-reference-note db ledger cross-referenced-account))
      ["Rule" "Times fired" "Accounts" "Detail (from the governor)"]
      (rows (map hard-check-row groups)))

     (section
      "Jurisdiction spec-basis coverage"
      (str "<code>banking.facts/coverage</code> over the jurisdictions the seeded accounts actually carry: "
           "<span class=\"num\">" (:covered cov) "</span> of <span class=\"num\">" (:requested cov)
           "</span> covered"
           (when (seq (:missing-jurisdictions cov))
             (str ", missing " (str/join ", " (map #(code* %) (:missing-jurisdictions cov)))))
           ". " (esc (:note cov)))
      ["ISO3" "Jurisdiction" "Owner authority" "Legal basis" "Required evidence" "Provenance"]
      (rows (map jurisdiction-row (sort used-jurisdictions))))

     (section
      "Human approval trail — and what the store actually kept"
      (str "Left half is the run's own audit fact; the right-most column is read back OUT of the store at "
           "render time by looking for an <code>approved-by</code> key in the registers that op writes. "
           "It is derived, not declared: if the store is later changed to keep the approver on a register "
           "it currently drops, this column starts saying <em>retained</em> without anyone editing this "
           "page. " (approver-disclosure trail))
      ["Op" "Account" "Decision" "Decided by (audit fact)" "Store register inspected" "Approver in the record?"]
      (rows (map approval-row trail)))

     (section
      "Registry drafts minted by this run"
      (str "The append-only book-of-record drafts <code>banking.registry</code> actually produced. Every one "
           "is a DRAFT with an unsigned certificate — signing is the banking operator's own act, not this "
           "actor's. No real core-banking system or clearing network was contacted.")
      ["Record id" "Kind" "Account" "Jurisdiction" "Mutability"]
      (rows (concat (map draft-row (store/settlement-history db))
                    (map draft-row (store/interbank-message-history db)))))

     (section
      (str "Audit ledger (this run — " (count ledger) " facts)")
      "Append-only decision-fact log: every commit, every hold, every rejection, in the order the actor produced them."
      ["Fact" "Op" "Account" "Basis" "Summary"]
      (rows (map ledger-row ledger)))

     "</main>\n"
     "<footer>\n"
     "  <p>Generated by <code>banking.render-html</code> from a real <code>banking.operation</code> → "
     "<code>banking.governor</code> → <code>banking.store</code> run driven through "
     "<code>langgraph.graph/run*</code>. Deterministic and timestamp-free: two consecutive builds are "
     "byte-identical.</p>\n"
     "</footer>\n"
     "</body></html>\n")))

;; ----------------------------- build-time invariants -----------------------------

(defn- assert-real-holds!
  "Invariants 1-6. THROWS; never warns. A generator that renders a page
  with no HARD hold in it has not demonstrated the thing this repo
  exists to demonstrate, and a page whose HARD-check section outlived
  the run that justified it is a lie with a table around it."
  [{:keys [db runs]}]
  (let [ledger (vec (store/ledger db))
        holds (hard-holds ledger)
        rules (into #{} (mapcat #(map :rule (:violations %)) holds))
        groups (hard-rule-groups ledger)]
    (println "LEDGER-FACTS\t" (count ledger))
    (println "HARD-HOLDS\t" (count holds))
    (println "DISTINCT-HARD-RULES\t" (count rules))

    ;; 1 -- at least one real HARD hold
    (when (zero? (count holds))
      (throw (ex-info (str "render-html: the run produced ZERO :governor-hold facts -- "
                           "refusing to write a console that shows no HARD hold")
                      {:ledger-facts (count ledger)})))

    ;; 2 -- evidence floor on DISTINCT rules
    (when (< (count rules) min-distinct-hard-rules)
      (throw (ex-info "render-html: fewer distinct HARD rules fired than the evidence floor requires"
                      {:fired (vec (sort-by str rules))
                       :count (count rules)
                       :floor min-distinct-hard-rules})))

    ;; 3 -- a HARD hold must never have asked a human
    (doseq [r runs]
      (let [ts (into #{} (map :t (:audit r)))]
        (when (and (contains? ts :governor-hold) (contains? ts :approval-requested))
          (throw (ex-info "render-html: a run that HARD-held ALSO escalated to a human approver"
                          {:thread (:thread r) :op (:op r) :subject (:subject r)})))))

    ;; 4 -- no rendered HARD-check row without a backing ledger rule
    (doseq [{:keys [rule]} groups]
      (when-not (contains? rules rule)
        (throw (ex-info "render-html: HARD-check row has no backing ledger fact" {:rule rule}))))

    ;; 5 -- the SOFT gate must have shown BOTH of its outcomes. Without
    ;; this floor an empty approval trail renders as a legitimate-looking
    ;; but empty table, and the derived attribution sentence degrades to
    ;; "nothing to attribute" -- silence that reads like a pass.
    (let [trail (approval-trail db runs)
          outcomes (frequencies (map :outcome trail))]
      (println "APPROVALS-GRANTED\t" (get outcomes :approval-granted 0))
      (println "APPROVALS-REJECTED\t" (get outcomes :approval-rejected 0))
      (when (zero? (get outcomes :approval-granted 0))
        (throw (ex-info (str "render-html: no approval was GRANTED -- the approval trail and the "
                             "approver-attribution probe would both be vacuous")
                        {:trail (count trail)})))
      (when (zero? (get outcomes :approval-rejected 0))
        (throw (ex-info "render-html: no approval was REJECTED -- the SOFT gate's other outcome was never demonstrated"
                        {:trail (count trail)}))))

    ;; 6 -- both actuation lifecycles must have actually minted a draft
    (let [n-set (count (store/settlement-history db))
          n-msg (count (store/interbank-message-history db))]
      (println "SETTLEMENT-DRAFTS\t" n-set)
      (println "INTERBANK-MESSAGE-DRAFTS\t" n-msg)
      (when (or (zero? n-set) (zero? n-msg))
        (throw (ex-info "render-html: an actuation lifecycle minted no registry draft"
                        {:settlements n-set :interbank-messages n-msg}))))

    {:holds (count holds) :rules (vec (sort-by str rules))}))

(defn -main [& args]
  (let [out (or (first args) "docs/samples/operator-console.html")
        result (run-demo!)
        {:keys [holds rules]} (assert-real-holds! result)
        html (render result)]
    (spit out html)
    (println "wrote" out
             (str "(" (count (store/ledger (:db result))) " ledger facts, "
                  holds " HARD holds over " (count rules) " distinct rules, "
                  (count (store/settlement-history (:db result))) " settlement drafts, "
                  (count (store/interbank-message-history (:db result))) " interbank-message drafts, "
                  (count html) " bytes)"))
    (println "HARD-RULES\t" (str/join " " (map str rules)))))
